[workspace]
resolver = "2"
members = ["core", "cli"]

[workspace.package]
edition = "2024"
authors = ["alexandretrotel"]
license-file = "LICENSE"
repository = "https://github.com/alexandretrotel/todo-tree"
homepage = "https://github.com/alexandretrotel/todo-tree"

[profile.release]
lto = true
codegen-units = 1
strip = true
